// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgpONWUwLhpGVlvPD--UEDGHfMNca-fzQ',
    appId: '1:826055344336:web:79f5e6504619ed2405ded5',
    messagingSenderId: '826055344336',
    projectId: 'chat-app-9bfba',
    authDomain: 'chat-app-9bfba.firebaseapp.com',
    storageBucket: 'chat-app-9bfba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJutmNTewa5WrR5diCPql6fmBNkPXOAD4',
    appId: '1:826055344336:android:1cbff8e1526d7e7c05ded5',
    messagingSenderId: '826055344336',
    projectId: 'chat-app-9bfba',
    storageBucket: 'chat-app-9bfba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQWfQ5yXDuunHGI3f38B51KMclU48qXe0',
    appId: '1:826055344336:ios:843c0e4367e461b805ded5',
    messagingSenderId: '826055344336',
    projectId: 'chat-app-9bfba',
    storageBucket: 'chat-app-9bfba.appspot.com',
    iosClientId: '826055344336-5ku7ils2q02a5mcqn2924pfbtog62tvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQWfQ5yXDuunHGI3f38B51KMclU48qXe0',
    appId: '1:826055344336:ios:843c0e4367e461b805ded5',
    messagingSenderId: '826055344336',
    projectId: 'chat-app-9bfba',
    storageBucket: 'chat-app-9bfba.appspot.com',
    iosClientId: '826055344336-5ku7ils2q02a5mcqn2924pfbtog62tvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
